// Generated by CoffeeScript 1.6.1
(function() {

  $().ready(function() {
    $("#newCoffee").click(function() {
      var coffee, name;
      name = prompt("Add new coffee");
      coffee = $("<li>" + name + "</li>");
      return $('ul').append(coffee);
    });
    $('.box').mouseenter(function() {
      return $(this).show();
    });
    return $('.box').mouseleave(function() {
      return $(this).fade(1000);
    });
  });

}).call(this);
