// Generated by CoffeeScript 1.6.1
(function() {

  $().ready(function() {
    $('h1').click(function() {
      return alert("You clicked this");
    });
    $('p').click(function() {
      return alert("you cliked the other thing");
    });
    return $('ul >  li').click(function() {
      return alert("you clicked the list element");
    });
  });

}).call(this);
