// Generated by CoffeeScript 1.6.1
(function() {
  var Animal, sammy;

  Animal = (function() {

    function Animal(name, type) {
      this.name = name;
      this.type = type;
    }

    Animal.prototype.move = function() {
      return alert("Slithering...");
    };

    return Animal;

  })();

  sammy = new Animal("Sammy", "Python");

  alert(sammy.name);

  alert(sammy.type);

  sammy.move;

}).call(this);
