// Generated by CoffeeScript 1.6.1
(function() {
  var people, x, _i, _len;

  people = {
    chad: {
      name: "Chad",
      age: 20
    },
    momo: {
      name: "Momo",
      age: 6
    },
    heather: {
      name: "Heather",
      age: 18
    }
  };

  for (_i = 0, _len = people.length; _i < _len; _i++) {
    x = people[_i];
    alert(x.name);
  }

}).call(this);
